import os
import json
from config import DATA_DIR

SETTINGS_PATH = os.path.join(DATA_DIR, "ui_settings.json")

class Translator:
    def __init__(self):
        self.lang = "en"
        self.load_settings()
        
        self.dict = {
            # Navigation
            "nav_dashboard": {"en": "📊 Dashboard", "fa": "📊 داشبورد"},
            "nav_registry": {"en": "🤝 Unit Registry", "fa": "🤝 ثبت واحدها"},
            "nav_assistants": {"en": "🤖 AI Assistants", "fa": "🤖 دستیارهای هوش مصنوعی"},
            "nav_mission": {"en": "📡 Mission Control", "fa": "📡 کنترل ماموریت"},
            "nav_logs": {"en": "🗄️ Secure Logs", "fa": "🗄️ لاگ‌های امنیتی"},
            "nav_tutorial": {"en": "📖 Tutorial & Help", "fa": "📖 آموزش و راهنما"},
            
            # Dashboard
            "dash_title": {"en": "🛡️ AIBOS Management Dashboard", "fa": "🛡️ داشبورد مدیریت AIBOS"},
            "dash_loading": {"en": "Loading data securely...", "fa": "در حال بارگذاری امن داده‌ها..."},
            "dash_btn_refresh": {"en": "Refresh Status", "fa": "بروزرسانی وضعیت"},
            
            # Unit Registry
            "unit_title": {"en": "Network Units Directory", "fa": "فهرست واحدهای شبکه"},
            "unit_del_btn": {"en": "Delete Selected Unit", "fa": "حذف واحد انتخاب شده"},
            "unit_reg_title": {"en": "Register New Trusted Unit", "fa": "ثبت واحد مورد اعتماد جدید"},
            "unit_inp_id": {"en": "Remote Unit UUID", "fa": "شناسه (UUID) واحد راه دور"},
            "unit_inp_name": {"en": "Display Name", "fa": "نام نمایشی"},
            "unit_inp_role": {"en": "Role & Max Permitted Security Level:", "fa": "نقش و حداکثر سطح امنیت مجاز:"},
            "unit_inp_pub_ed": {"en": "Remote Ed25519 Public Key (Leave blank for initial setup)", "fa": "کلید عمومی Ed25519 (برای تنظیم اولیه خالی بگذارید)"},
            "unit_inp_pub_x": {"en": "Remote X25519 Public Key (Leave blank for initial setup)", "fa": "کلید عمومی X25519 (برای تنظیم اولیه خالی بگذارید)"},
            "unit_btn_add": {"en": "Register & Generate Local Keys", "fa": "ثبت و تولید کلیدهای محلی"},
            
            # Assistants
            "ast_title": {"en": "AI Routing Assistants Directory", "fa": "فهرست دستیارهای مسیریابی هوش مصنوعی"},
            "ast_reg_title": {"en": "Register New Assistant", "fa": "ثبت دستیار جدید"},
            "ast_inp_name": {"en": "Assistant Name", "fa": "نام دستیار"},
            "ast_inp_desc": {"en": "Description for AI Selection logic", "fa": "توضیحات برای منطق انتخاب هوش مصنوعی"},
            "ast_inp_url": {"en": "API URL (Must contain {TEXT})", "fa": "آدرس API (باید شامل {TEXT} باشد)"},
            "ast_btn_add": {"en": "Register Assistant", "fa": "ثبت دستیار"},
            
            # Mission Control
            "mis_title": {"en": "Create Secure Mission Request", "fa": "ایجاد درخواست ماموریت امن"},
            "mis_target": {"en": "Target Destination:", "fa": "مقصد هدف:"},
            "mis_req": {"en": "Natural Language Request:", "fa": "درخواست به زبان طبیعی:"},
            "mis_btn_send": {"en": "Encrypt & Process Mission", "fa": "رمزنگاری و پردازش ماموریت"},
            "mis_btn_processing": {"en": "Processing via Local AI...", "fa": "در حال پردازش توسط هوش مصنوعی محلی..."},
            "mis_import_title": {"en": "Offline Inbound Payloads", "fa": "بسته‌های ورودی آفلاین"},
            "mis_btn_in": {"en": "📥 Import Incoming Mission (Execute)", "fa": "📥 وارد کردن ماموریت ورودی (اجرا)"},
            "mis_btn_out": {"en": "📬 Import Mission Response (View Result)", "fa": "📬 وارد کردن پاسخ ماموریت (مشاهده نتیجه)"},
            
            # Logs
            "log_title": {"en": "Cryptographic Tamper-Evident Ledger", "fa": "دفتر کل رمزنگاری شده و ضد دستکاری"},
            "log_btn": {"en": "Pull Secure Logs", "fa": "دریافت لاگ‌های امنیتی"},
            
            # Tutorial
            "tut_title": {"en": "📚 AI BOS - Comprehensive Tutorial", "fa": "📚 آموزش جامع AIBOS"},
            "tut_content": {
                "en": """
<h2>Welcome to AI BOS (Artificial Intelligence Based Operations Security)</h2>
<p>This system guarantees secure, decentralized communication using local AI evaluation and zero-trust cryptography.</p>

<h3>Step 1: Cryptographic Handshake (Defining Units)</h3>
<p>Before units can communicate, they must formally exchange public keys.</p>
<ol>
<li>Go to <b>Unit Registry</b>. Enter an ID and Name for the remote unit. <b>Leave the Public Keys blank</b> and click Register.</li>
<li>The system will generate your unique private/public keys for this specific relationship. Copy your public keys.</li>
<li>Go to the other computer/unit. Register your unit there, pasting the keys you just copied.</li>
<li>Copy the keys generated by the other unit, come back to your UI, type the EXACT SAME ID, paste their keys, and click Register again. Your keys are now permanently linked!</li>
</ol>

<h3>Step 2: Defining AI Assistants (Optional)</h3>
<p>If your unit is a Destination, you can connect it to internal APIs. Go to <b>AI Assistants</b> and register a URL like <code>http://internal.api/?query={TEXT}</code>. When you approve an incoming mission, the AI will automatically fetch data from this API and encrypt the result back to the sender.</p>

<h3>Step 3: Creating and Transferring Missions</h3>
<p>Go to <b>Mission Control</b>. Select a destination and type a prompt (e.g., "Get the sensor data").</p>
<ul>
<li>The AI will score it. If it is a medium risk (Score 3-8), a popup will ask for your approval.</li>
<li>Upon approval, an encrypted <code>.aibos</code> file is saved in your <code>transfers/</code> folder.</li>
<li>Move this file via USB or secure network to the destination unit.</li>
<li>The destination operator clicks <b>Import Incoming Mission</b>. Their AI will check it, prompt them, and execute it!</li>
<li>If the destination returns a response file, you can click <b>Import Mission Response</b> to decrypt and view it safely.</li>
</ul>
                """,
                "fa": """
<h2 dir="rtl">به سیستم مدیریت امنیتی هوش مصنوعی (AI BOS) خوش آمدید</h2>
<p dir="rtl">این سیستم ارتباطات امن و غیرمتمرکز را با استفاده از ارزیابی هوش مصنوعی محلی و رمزنگاری اعتماد صفر (Zero-Trust) تضمین می‌کند.</p>

<h3 dir="rtl">مرحله 1: دست‌دهی رمزنگاری (تعریف واحدها)</h3>
<p dir="rtl">قبل از ارتباط، واحدها باید کلیدهای عمومی خود را تبادل کنند.</p>
<ol dir="rtl">
<li>به بخش <b>ثبت واحدها</b> بروید. شناسه و نام واحد راه دور را وارد کنید. <b>کلیدهای عمومی را خالی بگذارید</b> و روی ثبت کلیک کنید.</li>
<li>سیستم کلیدهای اختصاصی شما را برای این رابطه تولید می‌کند. کلیدهای عمومی خود را کپی کنید.</li>
<li>به سیستم دیگر بروید. واحد خود را آنجا ثبت کرده و کلیدهایی که کپی کردید را وارد کنید.</li>
<li>کلیدهای تولید شده توسط واحد دوم را کپی کنید، به سیستم خود برگردید، دقیقاً همان شناسه قبلی را وارد کنید، کلیدهای جدید را پیست کرده و دوباره ثبت کنید. اکنون شما متصل هستید!</li>
</ol>

<h3 dir="rtl">مرحله 2: تعریف دستیارهای هوش مصنوعی (اختیاری)</h3>
<p dir="rtl">اگر واحد شما مقصد است، می‌توانید آن را به APIهای داخلی متصل کنید. به <b>دستیارهای هوش مصنوعی</b> بروید و یک آدرس مانند <code>http://api/?query={TEXT}</code> ثبت کنید. هنگام تایید یک ماموریت ورودی، هوش مصنوعی داده‌ها را از این API گرفته و نتیجه را برای فرستنده رمزنگاری می‌کند.</p>

<h3 dir="rtl">مرحله 3: ایجاد و انتقال ماموریت‌ها</h3>
<p dir="rtl">به بخش <b>کنترل ماموریت</b> بروید. یک مقصد انتخاب کنید و درخواست خود را (مثلاً "داده‌های سنسور را دریافت کن") بنویسید.</p>
<ul dir="rtl">
<li>هوش مصنوعی به آن امتیاز می‌دهد. در صورت ریسک متوسط (امتیاز 3-8)، یک پنجره برای تایید شما باز می‌شود.</li>
<li>پس از تایید، یک فایل رمزنگاری شده <code>.aibos</code> در پوشه <code>transfers/</code> ذخیره می‌شود.</li>
<li>این فایل را از طریق USB یا شبکه به واحد مقصد منتقل کنید.</li>
<li>اپراتور مقصد روی <b>وارد کردن ماموریت ورودی</b> کلیک می‌کند تا آن را اجرا کند!</li>
<li>در صورت دریافت فایل پاسخ، روی <b>وارد کردن پاسخ ماموریت</b> کلیک کنید تا رمزگشایی و مشاهده شود.</li>
</ul>
                """
            }
        }

    def load_settings(self):
        if os.path.exists(SETTINGS_PATH):
            try:
                with open(SETTINGS_PATH, "r") as f:
                    self.lang = json.load(f).get("lang", "en")
            except:
                pass

    def save_settings(self, lang: str):
        self.lang = lang
        with open(SETTINGS_PATH, "w") as f:
            json.dump({"lang": lang}, f)

    def t(self, key: str) -> str:
        return self.dict.get(key, {}).get(self.lang, key)

# Create a global singleton instance
translator = Translator()
def tr(key: str) -> str:
    return translator.t(key)